# Generated by Django 5.1.1 on 2024-11-26 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_invitecollaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterunlockedbyuser",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.CreateModel(
            name="ProofOfPaymentByUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("method_of_payment", models.CharField(max_length=255)),
                ("image_data", models.BinaryField()),
                ("notes", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(default="pending", max_length=100)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_of_payment",
                        to="books.bookschapter",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs_of_payment_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proof of Payment By User",
                "verbose_name_plural": "Proof of Payment By User",
                "db_table": "proof_of_payment",
            },
        ),
    ]
