# Generated by Django 5.1.1 on 2024-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_chapterunlockedbyuser_status_proofofpaymentbyuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proofofpaymentbyuser",
            name="image_data",
        ),
        migrations.AddField(
            model_name="proofofpaymentbyuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="proof_of_payment_images/"
            ),
        ),
    ]
