# Generated by Django 5.1.1 on 2024-11-28 04:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_remove_proofofpaymentbyuser_image_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="generate_unique_slug", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="bookschapter",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="generate_unique_slug", unique=True
            ),
        ),
    ]
