# Generated by Django 5.1.1 on 2024-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0021_alter_books_slug_alter_bookschapter_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proofofpaymentbyuser",
            name="image",
        ),
        migrations.AlterField(
            model_name="books",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
